import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full w-full overflow-x-hidden `}>
        <div className="bg-primary flex items-center overflow-x-hidden justify-center h-screen w-screen">
          <Toaster />

          {children}
        </div>
      </body>
    </html>
  );
}
